/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedEntityConfig: typeof import('./components/entities/AdvancedEntityConfig.vue')['default']
    CircularDependencyAlert: typeof import('./components/dependencies/CircularDependencyAlert.vue')['default']
    CreateConfigurationDialog: typeof import('./components/configurations/CreateConfigurationDialog.vue')['default']
    DataPreviewTable: typeof import('./components/DataPreviewTable.vue')['default']
    DataSourceFormDialog: typeof import('./components/DataSourceFormDialog.vue')['default']
    DeleteConfirmationDialog: typeof import('./components/common/DeleteConfirmationDialog.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    EntityFormDialog: typeof import('./components/entities/EntityFormDialog.vue')['default']
    EntityListCard: typeof import('./components/entities/EntityListCard.vue')['default']
    ErrorAlert: typeof import('./components/common/ErrorAlert.vue')['default']
    ForeignKeyEditor: typeof import('./components/entities/ForeignKeyEditor.vue')['default']
    LoadingSkeleton: typeof import('./components/common/LoadingSkeleton.vue')['default']
    QueryBuilder: typeof import('./components/query/QueryBuilder.vue')['default']
    QueryCondition: typeof import('./components/query/QueryCondition.vue')['default']
    QueryEditor: typeof import('./components/query/QueryEditor.vue')['default']
    QueryResults: typeof import('./components/query/QueryResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaTreeView: typeof import('./components/SchemaTreeView.vue')['default']
    TableDetailsPanel: typeof import('./components/TableDetailsPanel.vue')['default']
    ValidationMessageList: typeof import('./components/validation/ValidationMessageList.vue')['default']
    ValidationPanel: typeof import('./components/validation/ValidationPanel.vue')['default']
  }
}
