/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedEntityConfig: typeof import('./components/entities/AdvancedEntityConfig.vue')['default']
    CircularDependencyAlert: typeof import('./components/dependencies/CircularDependencyAlert.vue')['default']
    ConfigurationDataSources: typeof import('./components/ConfigurationDataSources.vue')['default']
    CreateProjectDialog: typeof import('./components/projects/CreateProjectDialog.vue')['default']
    DataPreviewTable: typeof import('./components/DataPreviewTable.vue')['default']
    DataSourceFormDialog: typeof import('./components/DataSourceFormDialog.vue')['default']
    DataValidationConfig: typeof import('./components/validation/DataValidationConfig.vue')['default']
    DeleteConfirmationDialog: typeof import('./components/common/DeleteConfirmationDialog.vue')['default']
    DependencyGraph: typeof import('./components/dependencies/DependencyGraph.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    EntityDataPreview: typeof import('./components/entities/EntityDataPreview.vue')['default']
    EntityFormDialog: typeof import('./components/entities/EntityFormDialog.vue')['default']
    EntityListCard: typeof import('./components/entities/EntityListCard.vue')['default']
    EntityPreviewPanel: typeof import('./components/entities/EntityPreviewPanel.vue')['default']
    EntityResultsList: typeof import('./components/TestRun/EntityResultsList.vue')['default']
    ErrorAlert: typeof import('./components/common/ErrorAlert.vue')['default']
    FixedValuesGrid: typeof import('./components/entities/FixedValuesGrid.vue')['default']
    ForeignKeyEditor: typeof import('./components/entities/ForeignKeyEditor.vue')['default']
    ForeignKeyTester: typeof import('./components/entities/ForeignKeyTester.vue')['default']
    LoadingSkeleton: typeof import('./components/common/LoadingSkeleton.vue')['default']
    MetadataEditor: typeof import('./components/MetadataEditor.vue')['default']
    PreviewFixesModal: typeof import('./components/validation/PreviewFixesModal.vue')['default']
    QueryBuilder: typeof import('./components/query/QueryBuilder.vue')['default']
    QueryCondition: typeof import('./components/query/QueryCondition.vue')['default']
    QueryEditor: typeof import('./components/query/QueryEditor.vue')['default']
    QueryResults: typeof import('./components/query/QueryResults.vue')['default']
    ReconciliationGrid: typeof import('./components/reconciliation/ReconciliationGrid.vue')['default']
    ReconciliationView: typeof import('./components/reconciliation/ReconciliationView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaTreeView: typeof import('./components/SchemaTreeView.vue')['default']
    SessionIndicator: typeof import('./components/SessionIndicator.vue')['default']
    SessionManager: typeof import('./components/SessionManager.vue')['default']
    SqlEditor: typeof import('./components/common/SqlEditor.vue')['default']
    SuggestionsPanel: typeof import('./components/entities/SuggestionsPanel.vue')['default']
    TableDetailsPanel: typeof import('./components/TableDetailsPanel.vue')['default']
    TestRunConfig: typeof import('./components/TestRun/TestRunConfig.vue')['default']
    TestRunProgress: typeof import('./components/TestRun/TestRunProgress.vue')['default']
    TestRunResults: typeof import('./components/TestRun/TestRunResults.vue')['default']
    ThemeColorPicker: typeof import('./components/ThemeColorPicker.vue')['default']
    ValidationMessageList: typeof import('./components/validation/ValidationMessageList.vue')['default']
    ValidationPanel: typeof import('./components/validation/ValidationPanel.vue')['default']
    ValidationSuggestion: typeof import('./components/validation/ValidationSuggestion.vue')['default']
    YamlEditor: typeof import('./components/common/YamlEditor.vue')['default']
  }
}
